### ISSUE TITLE
Did you forget to push code samples you presented?

### ISSUE THREAD

**Issue by pnowosie** [illarionvk/warsawjs-lodash#1]
Hello Illarion,

I've seen you presentation on WarsawJS about lodash (only via stream). It was pleasure, great job Sir ;)
Then I told my colleague about yours presentation and I expected to have a look at code samples here. 

Could you please publish them? Thanks!

**Comment by illarionvk** [comment]
Hello Pawel,

Thank you for your feedback, I'm glad you liked my presentation!

I've added the links to repo README file. The presentation slides are published on Github Pages:

[https://github.com/illarionvk/warsawjs-lodash](https://github.com/illarionvk/warsawjs-lodash)

"List duplicates in array" example:

[https://github.com/illarionvk/warsawjs-find-duplicates-in-array](https://github.com/illarionvk/warsawjs-find-duplicates-in-array)
